### ISSUE TITLE
This seems to be broken

### ISSUE THREAD

**Issue by davjhan** [hood/bump.ts#1]
Hey, just wanted to let you know, that this engine seems to be broken. There doesn't seem to be any Collisions generated no matter what. The basic example in the Readme doesn't work (boxes don't react at all).

**Comment by hood** [comment]
Hi, and thank you for using the library. It seems like you've having trouble consuming it, as it's currently in use in several published games, and collisions are definitely there.

Could i ask you for a reproduction repo to check what's happening in your case? Meanwhile I'll have a check and see if I made any errors in the readme examples.

**Comment by davjhan** [comment]
Hey! First, thanks for writing this port, really appreciate it.

Here's a sample code using PIXI as a renderer.


https://github.com/hood/bump.ts/assets/10100613/99e6632c-5938-4bc2-b33a-f746d9578c56

As you can see, no box collides with each other, or the wall.


```ts
const Config = {
  STAGE_WIDTH: 640,
  STAGE_HALF_WIDTH: 320,
}
export function createApplication() {

  const app = new Application<HTMLCanvasElement>({
    width: Config.STAGE_WIDTH,
    height: Config.STAGE_HEIGHT,
    backgroundColor: '#eeeeee'
  });
  
  /* Init World*/
  const world = Bump.newWorld(100)
  
  /* Init Graphics */
  const gfx = new Graphics()
  app.stage.addChild(gfx)
  
  addWalls(world)
  const boxes = Array.from({length: 100}, (_, i) => {
    const id = world.add(shortid.generate(), Math.random() *  Config.STAGE_WIDTH, Math.random() * Config.STAGE_HEIGHT, 20, 20)
    return {
      id,
      direction: Vector.rotate(Vector.create(1, 0), random.float(Math.PI))
    }
  })
  
  app.ticker.add(() => {
    boxes.forEach(({id, direction}) => {
      const {x, y} = world.getRect(id)
      const SPEED = 1
      const newX = x + direction.x * SPEED
      const newY = y + direction.y * SPEED
      return world.move(
        id,
        newX,/* x */
        newY,/* y */
        () => 'slide'
      )
    })
  })
  
  /* Draw boxes*/
  app.ticker.add(() => {
    gfx.clear()
    world.getItems().forEach(({x, y, w, h}) => {
      gfx.lineStyle(1, Colors.Red)
      gfx.drawRect(x, y, w, h)
    })
  })
  
  return app
}

function addWalls(world: World) {
  const WALL_THICKNESS = 60
  world.add('left-wall', -WALL_THICKNESS, -WALL_THICKNESS, WALL_THICKNESS, Config.STAGE_HEIGHT + WALL_THICKNESS * 2)
  world.add('top-wall', -WALL_THICKNESS, -WALL_THICKNESS, Config.STAGE_WIDTH + WALL_THICKNESS * 2, WALL_THICKNESS)
  world.add('bot-wall', -WALL_THICKNESS, Config.STAGE_HEIGHT, Config.STAGE_WIDTH + WALL_THICKNESS * 2, WALL_THICKNESS)
  world.add('right-wall', Config.STAGE_WIDTH, -WALL_THICKNESS, WALL_THICKNESS, Config.STAGE_HEIGHT + WALL_THICKNESS * 2)
}
```

**Comment by hood** [comment]
Yes, there’s definitely something wrong with your code. When you move your entities using `world.move()`, it returns you the updated coordinates, calculated based on desired destination and the of collisions encountered while traveling. Just like the example in the readme, you should try doing something like

```typescript
const { x, y, collisions } = world.move("my-entity", destinationX, destinationY)
```


`collisions` contains a list of other entities your entity collided with, but you can ignore if it you don’t need to execute any kind of extra logic when it does.

**Comment by davjhan** [comment]
1. From my usage, Collisions has always been an empty array. Which makes sense because entities are moving as if no collisions happen. I have never been able to make a collision happen.

2. Even if I'm not using the returned object of move(), the entities should still move in a collision resolved way right? The returned x and y is the actual displacement based on the goal x and y, but nonetheless, the entity should have moved the reported displaced amount (which it never does).

**Comment by hood** [comment]
I’ve tried running your code, but it required me some modifications since there were a few broken things, no big changes tho. The result is looking fine to me, if i’m not missing anything:


https://github.com/hood/bump.ts/assets/56588510/815ca81f-a77e-4d41-8399-2d2c28aa8e07

the code is pretty much the same:
```ts
import { Application, Graphics } from 'pixi.js';
import Bump from 'bump-ts';

const Config = {
  STAGE_WIDTH: 640,
  STAGE_HEIGHT: 320,
};
export function createApplication() {
  const app = new Application({
    width: Config.STAGE_WIDTH,
    height: Config.STAGE_HEIGHT,
    backgroundColor: 0xa0a0a0,
  });

  /* Init World*/
  const world = Bump.newWorld(100);

  /* Init Graphics */
  const gfx = new Graphics();
  app.stage.addChild(gfx);

  addWalls(world);
  const boxes = Array.from({ length: 100 }, (_, i) => {
    const id = world.add(
      (Math.random() * Date.now()).toString(36),
      Math.random() * Config.STAGE_WIDTH,
      Math.random() * Config.STAGE_HEIGHT,
      20,
      20
    );
    return {
      id,
      direction: Math.random() * 360,
    };
  });

  const dirtox = (dir: number) => Math.cos((dir * Math.PI) / 180);
  const dirtoy = (dir: number) => Math.sin((dir * Math.PI) / 180);

  app.ticker.add(() => {
    boxes.forEach(({ id, direction }) => {
      const { x, y } = world.getRect(id);
      const SPEED = 1;
      const newX = x + dirtox(direction) * SPEED;
      const newY = y + dirtoy(direction) * SPEED;
      return world.move(id, newX /* x */, newY /* y */, () => 'slide');
    });
  });

  /* Draw boxes*/
  app.ticker.add(() => {
    gfx.clear();
    world.getItems().forEach(({ x, y, w, h }) => {
      gfx.lineStyle(1, 0xff00ff);
      gfx.drawRect(x, y, w, h);
    });
  });

  document.body.appendChild(app.view);

  return app;
}

function addWalls(world: any) {
  const WALL_THICKNESS = 60;
  world.add(
    'left-wall',
    -WALL_THICKNESS,
    -WALL_THICKNESS,
    WALL_THICKNESS,
    Config.STAGE_HEIGHT + WALL_THICKNESS * 2
  );
  world.add(
    'top-wall',
    -WALL_THICKNESS,
    -WALL_THICKNESS,
    Config.STAGE_WIDTH + WALL_THICKNESS * 2,
    WALL_THICKNESS
  );
  world.add(
    'bot-wall',
    -WALL_THICKNESS,
    Config.STAGE_HEIGHT,
    Config.STAGE_WIDTH + WALL_THICKNESS * 2,
    WALL_THICKNESS
  );
  world.add(
    'right-wall',
    Config.STAGE_WIDTH,
    -WALL_THICKNESS,
    WALL_THICKNESS,
    Config.STAGE_HEIGHT + WALL_THICKNESS * 2
  );
}

createApplication();
```

**Comment by davjhan** [comment]
First of all, thank you so much for putting in the effort to help me out and repro it! Really appreciate it. And apologies for using `shortid` and borrowing the Vector class from `matter-js` in the example. My bad. :) 

What's weird is that aside from this, my code and your code looks identical (esp. in how it uses the `bump-ts` api), but I can't repro the output in your video, which is acting as I expected it to behave.

For added context, I'm using 

```
"bump-ts": "^0.6.0",
```

**Comment by davjhan** [comment]
for what its worth, ` world.getItemsInCellPoint(x,y)` always returns an empty array for every `x,y` value. Even if i query an x and y coordinate that I _know_ is inside of a rect.

**Comment by davjhan** [comment]
Here's an even simplified demo. It just places 2 boxes. The first box moving into the second, stationary box.

Note:
-  I use `cellSize: 10000` so that I can abstract away the whole ~quadtree(?) from the issue.   
- I log the `{x, y, collisions} = world.move(...)` on each tick. Notice how collisions is always blank.
```ts
import {Application, Graphics} from "pixi.js";
import Bump from "bump-ts";

const Config = {
    STAGE_WIDTH: 640,
    STAGE_HEIGHT: 480,
}

export module BumpDemo2 {
    export function createApplication() {
        const app = new Application<HTMLCanvasElement>({
            width: Config.STAGE_WIDTH,
            height: Config.STAGE_HEIGHT,
            backgroundColor: '#eeeeee'
        });

        /* Init World*/
        const world = Bump.newWorld(10000)

        /* Init Graphics */
        const gfx = new Graphics()
        app.stage.addChild(gfx)

        world.add('going-right', 0, 0, 100, 100)
        world.add('wall', 400, 0, 50, 200)

        app.ticker.add(() => {
            const {x, y} = world.getRect('going-right')
            const {x: dx, y: dy, collisions} = world.move(
                'going-right',
                x + 1,
                y,
            )
            console.log(dx, dy, `collisions:`, collisions)
        })

        /* Draw boxes*/
        app.ticker.add(() => {
            gfx.clear()
            world.getItems().forEach(({x, y, w, h}) => {
                gfx.lineStyle(1, 0xFF0000)
                gfx.drawRect(x, y, w, h)
            })
        })
        return app
    }
}
```

https://github.com/hood/bump.ts/assets/10100613/bed10e5d-dd3e-47ad-88a2-6e55717cbe50

**Comment by hood** [comment]
Alright, eventually I figured this out. v0.6.1 should’ve never gotten published, but it happened. It is an experimental release with some performance enhancements, but it introduced regressions that I still have to sort out. Please use v0.5.0, I’m sorry this gave you some headaches, I was not aware that version existed anywhere outside my machine.

EDIT: 
I just uploaded a v0.6.2 version reverting the mess caused by 0.6.0.

**Comment by davjhan** [comment]
Thanks as always for the quick help!

🥳 IT WORKS!

<img width="756" alt="Screenshot 2024-02-28 at 5 57 09 PM" src="https://github.com/hood/bump.ts/assets/10100613/7900e0df-b219-4a70-9af1-dfa1f079670c">
